#!/usr/bin/env bash
# Generates .env pre-filled with values from the task-3 runbook
# (terraform/eksctl/k8s manifests: skills-eks, skills-alb, skills-db-proxy,
# skills-waf). Never writes AWS secrets to disk — credentials stay on the
# existing AWS CLI chain (aws configure / env vars / SSO).
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$backup"
  echo "기존 $ENV_FILE 발견 -> $backup 로 백업"
fi

cat > "$ENV_FILE" <<'EOF'
# Generated by scripts/generate-env.sh from the task-3 runbook.
# AWS credentials are intentionally left blank -- run `aws configure` or
# export AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY yourself if not already set.
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=ap-northeast-2

# WAF: skills-waf is attached to CloudFront -> scope CLOUDFRONT (WAF API/metrics
# run in us-east-1 for this scope; the app switches region automatically).
WAF_SCOPE=CLOUDFRONT
WAF_WEB_ACL_NAME=skills-waf

# Resource names from the task-3 runbook. Leave empty to fall back to
# auto-discovery (ALB target groups are LBC-generated and always auto-discovered
# regardless of this value).
ALB_NAME=skills-alb
RDS_PROXY_NAME=skills-db-proxy
EKS_CLUSTER_NAME=skills-eks

# Optional: WAF full logs CloudWatch Logs group (e.g. aws-waf-logs-skills).
# Leave empty to skip Logs Insights and rely on GetSampledRequests only.
WAF_LOG_GROUP=

# Kubernetes
TARGET_NAMESPACE=default
MAX_REPLICAS=20

# SQLite history/baseline store
DB_PATH=./data/dashboard.db
EOF

echo "$ENV_FILE 생성 완료"
echo

if command -v aws >/dev/null 2>&1; then
  if aws sts get-caller-identity >/dev/null 2>&1; then
    account=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "?")
    echo "[OK] AWS CLI 자격증명 확인됨 (account: $account) -- .env의 AWS_ACCESS_KEY_ID/SECRET 비워둬도 됨"
  else
    echo "[!] AWS CLI 자격증명 미설정 -- 'aws configure' 실행하거나 .env에 직접 입력하세요"
  fi
else
  echo "[!] aws CLI 없음 -- 자격증명은 AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY 환경변수 또는 .env에 직접 입력"
fi

if command -v kubectl >/dev/null 2>&1; then
  ctx=$(kubectl config current-context 2>/dev/null || true)
  if [ -n "$ctx" ]; then
    echo "[OK] kubeconfig 컨텍스트: $ctx"
  else
    echo "[!] kubeconfig 컨텍스트 없음 -- 'aws eks update-kubeconfig --name skills-eks --region ap-northeast-2' 실행하세요"
  fi
else
  echo "[!] kubectl 없음 -- kubeconfig 상태를 확인할 수 없음"
fi
