#!/usr/bin/env node
// Generates .env pre-filled with values from the task-3 runbook
// (terraform/eksctl/k8s manifests: skills-eks, skills-alb, skills-db-proxy,
// skills-waf). Never writes AWS secrets to disk -- credentials stay on the
// existing AWS CLI chain (aws configure / env vars / SSO).
//
// Plain Node (no bash/pwsh dependency) so it runs the same way under
// PowerShell, Git Bash, or a POSIX shell: `node scripts/generate-env.mjs`.

import { execFileSync } from "node:child_process";
import { existsSync, copyFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

const ENV_CONTENT = `# Generated by scripts/generate-env.mjs from the task-3 runbook.
# AWS credentials are intentionally left blank -- the dashboard reads the local
# aws CLI session on its own (설정 -> AWS 자격증명 -> aws CLI 세션 불러오기), and
# that is the path that keeps working when a temporary key expires. This file is
# only read at boot, so pinning keys here costs a restart to change.
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_SESSION_TOKEN=
AWS_REGION=ap-northeast-2

# WAF: skills-waf is attached to CloudFront -> scope CLOUDFRONT (WAF API/metrics
# run in us-east-1 for this scope; the app switches region automatically).
WAF_SCOPE=CLOUDFRONT
WAF_WEB_ACL_NAME=skills-waf

# Resource names from the task-3 runbook. Leave empty to fall back to
# auto-discovery (ALB target groups are LBC-generated and always auto-discovered
# regardless of this value).
ALB_NAME=skills-alb
RDS_PROXY_NAME=skills-db-proxy
EKS_CLUSTER_NAME=skills-eks

# Optional: WAF full logs CloudWatch Logs group (e.g. aws-waf-logs-skills).
# Leave empty to skip Logs Insights and rely on GetSampledRequests only.
WAF_LOG_GROUP=

# Kubernetes
TARGET_NAMESPACE=default
MAX_REPLICAS=20

# SQLite history/baseline store
DB_PATH=./data/dashboard.db
`;

if (existsSync(envPath)) {
  const stamp = new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\..+/, "")
    .replace("T", "");
  const backup = `${envPath}.bak.${stamp}`;
  copyFileSync(envPath, backup);
  console.log(`기존 .env 발견 -> ${backup} 로 백업`);
}

writeFileSync(envPath, ENV_CONTENT, "utf8");
console.log(".env 생성 완료\n");

function tryRun(cmd, args) {
  try {
    return execFileSync(cmd, args, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

const account = tryRun("aws", ["sts", "get-caller-identity", "--query", "Account", "--output", "text"]);
if (account) {
  console.log(`[OK] AWS CLI 자격증명 확인됨 (account: ${account}) -- .env의 AWS_ACCESS_KEY_ID/SECRET 비워둬도 됨`);
} else if (tryRun("aws", ["--version"]) !== null) {
  console.log("[!] AWS CLI 자격증명 미설정 -- 'aws configure' 또는 'aws sso login' 후 대시보드 설정 탭에서 'aws CLI 세션 불러오기'");
} else {
  console.log("[!] aws CLI 없음 -- 대시보드 설정 탭 > AWS 자격증명 > '키 직접 입력'에 붙여넣거나 .env에 직접 입력");
}

const ctx = tryRun("kubectl", ["config", "current-context"]);
if (ctx) {
  console.log(`[OK] kubeconfig 컨텍스트: ${ctx}`);
} else if (tryRun("kubectl", ["version", "--client"]) !== null) {
  console.log("[!] kubeconfig 컨텍스트 없음 -- 'aws eks update-kubeconfig --name skills-eks --region ap-northeast-2' 실행하세요");
} else {
  console.log("[!] kubectl 없음 -- kubeconfig 상태를 확인할 수 없음");
}
